In [1]:
import numpy as np

In [2]:
# Create a row vector

row_vector=np.array([1,2,3])
column_vector=np.array([[4],[5],[6]])

print("Row vector:",row_vector)
print("Column vector:", column_vector)

print("Row vector shape:", row_vector.shape)
print("Column vector shape:", column_vector.shape)


Row vector: [1 2 3]
Column vector: [[4]
 [5]
 [6]]
Row vector shape: (3,)
Column vector shape: (3, 1)


In [5]:
# Define two row vectors
a=np.array([1,2,3])
b=np.array([4,5,6])

In [6]:
# element wise addition
print("Addition:",a+b)

Addition: [5 7 9]


In [7]:
# element wise subtraction
print("Addition:",a-b)

Addition: [-3 -3 -3]


In [8]:
# scalar multiplication to a vector
scalar=2
print("Scalar multiplication:", scalar*a)

Scalar multiplication: [2 4 6]


In [9]:
# dot product
print("dot product", np.dot(a,b))

dot product 32


In [10]:
# Creating matrices
matrix_a=np.array([[1,2,3],[4,5,6]])
print(matrix_a.shape)

(2, 3)


In [13]:
# Identity matrix
print("Identitiy matrix:\n", np.identity(3))

Identitiy matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
# transpose 
print("Transpose:\n", matrix_a.T)
print("Shape of matrix A:", matrix_a.shape)
print("Shape of Transpose of matrix A:", matrix_a.T.shape)

Transpose:
 [[1 4]
 [2 5]
 [3 6]]
Shape of matrix A: (2, 3)
Shape of Transpose of matrix A: (3, 2)


In [17]:
matrix_b=np.array([[1,2,3],[4,5,6]])
print("Scalar mulitplication:\n", scalar*matrix_b)

Scalar mulitplication:
 [[ 2  4  6]
 [ 8 10 12]]


In [21]:
# Dot product(Matrix Multiplication)
print("Dot product:\n", np.dot(matrix_a,matrix_b.T))

Dot product:
 [[14 32]
 [32 77]]


In [23]:
# Solving a system of linear equations

# 2x+y=5
# x-3y=-1

A=np.array([[2,1],[1,-3]])
B=np.array([5,-1])
solution=np.linalg.solve(A,B)
print("Solution to the system of linear equation:", solution)

Solution to the system of linear equation: [2. 1.]


In [25]:
# Determinant and rank
C=np.array([[1,2,3],[0,4,5],[0,0,6]])
det_c=np.linalg.det(C)
print("Determinant of C:", det_c)

Determinant of C: 23.999999999999993


In [26]:
# Determinant of matrix
C=np.array([[1,2],[3,4]])
det_c=np.linalg.det(C)
print("Determinant of C:", det_c)

Determinant of C: -2.0000000000000004


In [27]:
# Rank of matrix
C=np.array([[1,2,3],[0,4,5],[0,0,6]])
rank_c=np.linalg.matrix_rank(C)
print("Rank of matrix:", rank_c)

Rank of matrix: 3


In [28]:
# Rank of matrix
C=np.array([[1,2],[3,4]])
rank_c=np.linalg.matrix_rank(C)
print("Rank of matrix:", rank_c)

Rank of matrix: 2
